---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed


  - name: copy index.html
    copy: 
     src: /home/ansadmin/index.html
     dest: /var/www/html
     mode: 0666 
