---
- name: My Test Playbook
  hosts: all
  become: true
  tasks: 
  - name: installing package
    yum: name="{{item.name}}" {{state=present}}
    with_items:
     - {name: 'httpd' ; value ='present'}
      
