---
- name: setup tomcat
  hosts: all
  become: yes
  tasks: 
  - name: Install java on Redhat
    yum: 
     name: java
     state: installed
    when: ansible_os_family == "RedHat"

  - name: Install java on Debian
    apt:
     name: default-jdk
     state: present
    when: ansible_os_family == "Debian"

  - name: Download tomcat
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.76/bin/apache-tomcat-8.5.76.tar.gz
     dest: /opt

  - name: Extract Tomcat
    unarchive:
     src: /opt/apache-tomcat-8.5.76.tar.gz
     dest: /opt
     remote_src: yes

  - name: providing execute permissions
    file :
       path: /opt/apache-tomcat-8.5.76/bin/startup.sh
       mode: 0777

        
  - name: Run Tomcat
    shell: ./startup.sh
    args:
     chdir : /opt/apache-tomcat-8.5.76/bin

 



